apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  labels:
    app: dask
    role: scheduler
spec:
  ports:
  - port: 8786
    targetPort: 8786
    name: scheduler
  - port: 8787
    targetPort: 8787
    name: bokeh
  - port: 9786
    targetPort: 9786
    name: http
  selector:
    app: dask
    role: scheduler
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask
      role: scheduler
  template:
    metadata:
      labels:
        app: dask
        role: scheduler
    spec:
      containers:
      - name: dask-scheduler
        image: jonahjoughin/pangeo-cluster:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "source activate dask-docker; dask-scheduler"]
        ports:
        - containerPort: 8786
        resources:
          requests:
            memory: "4096Mi"
            cpu: "1500m"
          limits:
            memory: "8192Mi"
            cpu: "3000m"
