apiVersion: v1
kind: Service
metadata:
  name: jupyter-server
  labels:
    app: jupyter
    role: server
spec:
  ports:
  - port: 8888
    targetPort: 8888
    name: http
  selector:
    app: jupyter
    role: server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
      role: server
  template:
    metadata:
      labels:
        app: jupyter
        role: server
    spec:
      containers:
      - name: jupyter-server
        image: jonahjoughin/pangeo-cluster:latest
        imagePullPolicy: Always
        command: ["jupyter"]
        args: ["notebook", "--allow-root", "--config", "notebook_config.py"]
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: "4096Mi"
            cpu: "1000m"
          limits:
            memory: "8192Mi"
            cpu: "2000m"
